// Mocks generated by Mockito 5.4.0 from annotations
// in pokedex_challenge_davidfernandes/test/pokedex_test/pokedex_api_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_challenge_davidfernandes/src/models/pokemon_model.dart'
    as _i4;

import 'pokedex_api_provider_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PokedexApiProviderTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexApiProviderTest extends _i1.Mock
    implements _i2.PokedexApiProviderTest {
  MockPokedexApiProviderTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PokemonSimpleResult>> getPokemons(
          {required int? offSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {#offSet: offSet},
        ),
        returnValue: _i3.Future<List<_i4.PokemonSimpleResult>>.value(
            <_i4.PokemonSimpleResult>[]),
      ) as _i3.Future<List<_i4.PokemonSimpleResult>>);
  @override
  _i3.Future<_i4.PokemonModel?> getPokemonDetails({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetails,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i4.PokemonModel?>.value(),
      ) as _i3.Future<_i4.PokemonModel?>);
  @override
  _i3.Future<List<_i4.PokemonModel>> getEvolutions(
          {required _i4.PokemonModel? pokemon}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutions,
          [],
          {#pokemon: pokemon},
        ),
        returnValue:
            _i3.Future<List<_i4.PokemonModel>>.value(<_i4.PokemonModel>[]),
      ) as _i3.Future<List<_i4.PokemonModel>>);
}
